context:
  name: tryton
  version: 5.0.33

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/tryton/tryton/archive/refs/tags/tryton-${{ version }}.tar.gz
  sha256: c161a97bf9e0ee054d2289330a7b807190494c18fd7c073702c48c71f70a77e6

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.8
    - setuptools
  run:
    - python >=3.7,<3.8
    - cairo >=1.16,<1.17
    - python-dateutil
    - pygobject <=3.44,<3.45
    - gtk3
    - librsvg

tests:
  - python:
      imports:
        - tryton
      pip_check: true

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tryton is business software, ideal for companies of any size, easy to use, complete and 100% Open Source.
  homepage: https://www.tryton.org/
  repository: https://github.com/tryton/tryton

extra:
  recipe-maintainers:
    - looooo
