context:
  name: tryton
  version: 7.4.3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/tryton/tryton/archive/refs/tags/tryton-${{ version }}.tar.gz
  sha256: 41c6234d6db93a964bd08435b464b2ea58a4a5b25fe6793e9ea14af8522d1a45
  patches:
    - python313.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install ./tryton --no-deps -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - cairo
    - python-dateutil
    - pygobject
    - gtk3
    - librsvg

tests:
  - python:
      imports:
        - tryton
      pip_check: true

about:
  license: GPL-3.0-or-later
  license_file: tryton/COPYRIGHT
  summary: Tryton is business software, ideal for companies of any size, easy to use, complete and 100% Open Source.
  homepage: https://www.tryton.org/
  repository: https://github.com/tryton/tryton

extra:
  recipe-maintainers:
    - looooo
